diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
init.defaultbranch=master
core.editor="C:\Users\cfraz\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Carlos Felippe
user.email=carlos.azevedo@indicium.tech
init.defaultbranch=master
credential.helper=manager
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/cfrazevedo/cfrazevedo.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
user.name=cfrazevedo
user.email=cfrazevedo@gmail.com
